version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: lifemaxxing-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: lifemaxxing_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - lifemaxxing-network-dev

  # Backend API (Development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lifemaxxing-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/lifemaxxing_dev?schema=public
      JWT_SECRET: dev_jwt_secret_key
      UPLOAD_PATH: ./uploads
      MAX_FILE_SIZE: 5242880
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_data_dev:/app/uploads
    depends_on:
      - postgres
    networks:
      - lifemaxxing-network-dev
    command: >
      sh -c "
        npx prisma migrate dev --name init &&
        npx prisma db seed &&
        npm run dev
      "

  # Database administration tool
  adminer:
    image: adminer:latest
    container_name: lifemaxxing-adminer-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - lifemaxxing-network-dev

volumes:
  postgres_data_dev:
    driver: local
  uploads_data_dev:
    driver: local

networks:
  lifemaxxing-network-dev:
    driver: bridge 